import Foundation
import VibeBuddyKit

/// The facts under a handoff document, read from what the Mac already
/// recorded about one session: the lifecycle journal (rounds, status), the
/// tool ledger (files edited, commands run with exit codes) and a live git
/// probe of the checkout. Nothing here is generated by a model, and nothing
/// is written: the ledgers are decoded directly, never through the types
/// that prune and persist them.
///
/// The writer of a handoff supplies its own Session key; this tool validates
/// that the key was observed and never picks "the most recent session"
/// (ADR-0019). Every section states what its source can and cannot report.
public enum HandoffFacts {
    public static let toolName = "vibebuddy_handoff_facts"
    public static let defaultCommands = 20
    public static let maxCommands = 50

    public static var definition: [String: Any] {
        ["name": toolName, "title": "Handoff facts",
         "description": "Read the recorded facts for one session before writing a handoff: rounds ended, the checkout's git HEAD and dirty files now, files edited, commands run with exit codes, and what the observation path could not see. Pass your own session key; the tool never picks a session for you and never generates text.",
         "inputSchema": ["type": "object", "properties": [
            "key": ["type": "string", "minLength": 1, "description": "Session key <agent>:<native id> (claude-code, codex, cursor, grok-build) or a vibebuddy://session/ reference; your own session's id."],
            "commands": ["type": "integer", "minimum": 1, "maximum": maxCommands, "default": defaultCommands, "description": "How many of the most recent commands to list (default 20, at most 50)."],
            "cwd": ["type": "string", "minLength": 1, "description": "Absolute checkout path to probe with git; otherwise derived from the files the session edited."]
         ], "required": ["key"], "additionalProperties": false],
         "annotations": ["readOnlyHint": true, "destructiveHint": false, "idempotentHint": true, "openWorldHint": false]]
    }

    /// Where the daemon keeps its ledgers. `VIBEBUDDY_FACTS_DIRECTORY` points a
    /// test or an isolated run at another directory.
    public static func directory(environment: [String: String]) -> URL {
        if let override = environment["VIBEBUDDY_FACTS_DIRECTORY"], override.hasPrefix("/") {
            return URL(fileURLWithPath: override)
        }
        return LifecycleJournalLocation.defaultURL().deletingLastPathComponent()
    }

    /// The git side of the facts, injectable so tests need no repository.
    public struct GitProbe: Sendable {
        public var probe: @Sendable (String) -> GitState?
        public init(probe: @escaping @Sendable (String) -> GitState?) { self.probe = probe }
        public static let live = GitProbe { cwd in GitState.probe(cwd: cwd) }
    }

    public struct GitState: Equatable, Sendable {
        public var root: String
        public var head: String?
        public var branch: String?
        /// `git status --porcelain` lines, at most `statusLimit`; `truncated` says if more existed.
        public var status: [String]
        public var truncated: Bool
        public static let statusLimit = 20
        public init(root: String, head: String?, branch: String?, status: [String], truncated: Bool) {
            self.root = root; self.head = head; self.branch = branch; self.status = status; self.truncated = truncated
        }

        /// Read-only git, arguments never through a shell; nil when the path is
        /// not inside an accessible repository. Reuses the bounded runner the
        /// workspace-changes reader uses, with the same lock-free flags.
        public static func probe(cwd: String) -> GitState? {
            guard cwd.hasPrefix("/"), FileManager.default.fileExists(atPath: cwd),
                  let top = WorkspaceChangesReader.run(cwd, ["rev-parse", "--show-toplevel"], cap: 8192), top.code == 0 else { return nil }
            let root = top.text.trimmingCharacters(in: .whitespacesAndNewlines)
            let head = WorkspaceChangesReader.run(root, ["rev-parse", "--short=12", "HEAD"], cap: 8192)
                .flatMap { $0.code == 0 ? $0.text.trimmingCharacters(in: .whitespacesAndNewlines) : nil }
            let branch = WorkspaceChangesReader.run(root, ["rev-parse", "--abbrev-ref", "HEAD"], cap: 8192)
                .flatMap { $0.code == 0 ? $0.text.trimmingCharacters(in: .whitespacesAndNewlines) : nil }
            var lines: [String] = []
            var truncated = false
            if let status = WorkspaceChangesReader.run(root, ["status", "--porcelain=v1", "--untracked-files=normal", "-z"], cap: 64_000), status.code == 0 {
                let all = status.text.split(separator: "\0").map(String.init).filter { !$0.isEmpty }
                lines = Array(all.prefix(statusLimit))
                truncated = status.truncated || all.count > statusLimit
            }
            return GitState(root: root, head: head, branch: branch, status: lines, truncated: truncated)
        }
    }

    // MARK: call

    public static func call(arguments: [String: Any], directory: URL, git: GitProbe = .live, now: Date = Date()) throws -> String {
        for (name, value) in arguments {
            guard ["key", "commands", "cwd"].contains(name) else {
                throw HistoryToolError.invalidArguments("facts accepts only key, commands and cwd.")
            }
            if name == "key" || name == "cwd" { guard value is String else { throw HistoryToolError.invalidArguments("Invalid argument: \(name)") } }
        }
        guard let rawKey = arguments["key"] as? String else { throw HistoryToolError.invalidArguments("Missing argument: key") }
        let limit = min(max((arguments["commands"] as? NSNumber)?.intValue ?? defaultCommands, 1), maxCommands)
        let requestedCwd = (arguments["cwd"] as? String).flatMap { $0.hasPrefix("/") ? URL(fileURLWithPath: $0).standardizedFileURL.path : nil }
        if arguments["cwd"] != nil, requestedCwd == nil { throw HistoryToolError.invalidArguments("cwd must be an absolute path.") }

        let journalURL = directory.appendingPathComponent("lifecycle-journal.json")
        let ledgerURL = directory.appendingPathComponent("tool-ledger.json")
        let journal = LifecycleJournal.readEntries(url: journalURL)
        let ledger = readLedger(url: ledgerURL)

        // A bare native id (what a hook or status line shows) is accepted when
        // the journal knows exactly one agent for it; otherwise the candidates
        // are listed and nothing is guessed.
        let reference: HistorySessionReference
        if !rawKey.contains(":") {
            let agents = Set(journal.entries.filter { $0.sessionID == rawKey }.map(\.agent))
            let keys = agents.compactMap(historyAgent).map { $0.keyName + ":" + rawKey }.sorted()
            if keys.isEmpty, ledger[rawKey] != nil {
                return "Native id \(line(rawKey)) has tool calls but no lifecycle record; pass a full key <agent>:\(line(rawKey)) so the agent is not guessed."
            }
            guard keys.count == 1 else {
                return keys.isEmpty
                    ? "No observation of native id \(line(rawKey)); pass a full key <agent>:<id> to see what is recorded under it."
                    : (["Ambiguous native id \(line(rawKey)); pass a full key:"] + keys.map { "- " + $0 }).joined(separator: "\n")
            }
            reference = try HistorySessionReference(keys[0])
        } else {
            reference = try HistorySessionReference(rawKey)
        }
        let agentKind = kind(of: reference.agent)
        let entries = journal.entries.filter { $0.sessionID == reference.nativeID && $0.agent == agentKind }
            .sorted { $0.timestamp < $1.timestamp }
        let records = (ledger[reference.nativeID] ?? []).sorted { $0.observedAt < $1.observedAt }
        let otherAgent = journal.entries.first { $0.sessionID == reference.nativeID && $0.agent != agentKind }?.agent
        let stampNow = iso(now)
        guard !entries.isEmpty || !records.isEmpty else {
            // Not an error: the key is well formed, the Mac just never saw it.
            var lines = ["Source session: \(reference.key)", "Ticket: unknown", "Branch: unknown", "Worktree: unknown", "",
                         "## Facts (recorded by VibeBuddy, as of \(stampNow))",
                         "- Not recorded: no observation of \(reference.key) in the lifecycle journal or tool ledger (both keep seven days). The session did not report to this Mac, or is older than the retention window."]
            if let otherAgent { lines.append("- Note: that native id was observed for \(otherAgent.displayName); check the key's agent prefix.") }
            lines.append("- Data: " + freshness(journalURL: journalURL, ledgerURL: ledgerURL, journalRead: journal.exists, ledgerRead: !ledger.isEmpty,
                                                journalOldest: journal.entries.map(\.timestamp).min()))
            return lines.joined(separator: "\n")
        }

        // Checkout: the writer's word first, then the repository the edited files live in.
        let edited = editedFiles(records)
        var checkout: String?
        var checkoutOrigin = "unknown"
        if let requestedCwd {
            checkout = requestedCwd; checkoutOrigin = "from cwd"
        } else if let derived = derivedCheckout(edited, git: git) {
            checkout = derived; checkoutOrigin = "derived from edited files"
        }
        let state = checkout.flatMap { git.probe($0) }
        let stamp = stampNow

        var out: [String] = []
        out.append("Source session: \(reference.key)")
        out.append("Ticket: unknown")
        out.append("Branch: \(state?.branch ?? "unknown")")
        out.append("Worktree: \(state?.root ?? checkout ?? "unknown")")
        out.append("")
        out.append("## Facts (recorded by VibeBuddy, as of \(stamp))")
        out.append(contentsOf: lifecycleLines(entries, agent: reference.agent, now: now))
        out.append("- Checkout: \(checkout.map(line) ?? "unknown") (\(checkoutOrigin))")
        out.append(contentsOf: gitLines(state, checkout: checkout, stamp: stamp))
        let tickets = ticketCandidates(edited)
        out.append("- Tickets touched: " + (tickets.isEmpty ? "none seen" : tickets.map(line).joined(separator: ", ")))
        out.append(contentsOf: editedLines(edited))
        out.append(contentsOf: commandLines(records, limit: limit))
        out.append("- Coverage: " + coverage(records, agent: reference.agent))
        out.append("- Data: " + freshness(journalURL: journalURL, ledgerURL: ledgerURL, journalRead: journal.exists, ledgerRead: !ledger.isEmpty,
                                          journalOldest: journal.entries.map(\.timestamp).min()))
        return out.joined(separator: "\n")
    }

    // MARK: sections

    private static func lifecycleLines(_ entries: [LifecycleJournalEntry], agent: SessionHistoryAgent, now: Date) -> [String] {
        guard let first = entries.first, let last = entries.last else {
            return ["- Agent: \(agent.displayName) · lifecycle not recorded (tool calls only)"]
        }
        var lines = ["- Agent: \(agent.displayName) · first seen \(iso(first.timestamp)) · last activity \(iso(last.timestamp))"]
        let stops = entries.filter { $0.event == "stop" }
        let completed = Set(entries.compactMap { $0.completionID }).count
        let failed = entries.contains { $0.failed == true }
        var status = "- Rounds ended: \(stops.count) stop event(s), \(completed) completion id(s)"
        if let s = last.status { status += " · last status: \(s.rawValue)" }
        if let wait = last.waitKind { status += " (\(wait.rawValue))" }
        if last.hasUnreadCompletion == true { status += " · completion unread" }
        else if let ack = last.acknowledgedCompletionID, ack == last.completionID, last.completionID != nil { status += " · completion read" }
        status += failed ? " · a round failed" : " · no failed round recorded"
        lines.append(status)
        let acknowledged = entries.filter { $0.event == "completionAcknowledged" || $0.event == "completionMarkedUnread" }
        if !acknowledged.isEmpty {
            lines.append("- Read state changes: " + acknowledged.map { "\($0.event) \(iso($0.timestamp))" }.joined(separator: "; "))
        }
        return lines
    }

    private static func gitLines(_ state: GitState?, checkout: String?, stamp: String) -> [String] {
        guard let checkout else { return ["- Git: not probed (no checkout)"] }
        guard let state else { return ["- Git: \(line(checkout)) is not an accessible git repository, or git did not answer within the time limit"] }
        var lines = ["- Git: HEAD \(state.head ?? "unknown") on \(state.branch ?? "unknown") · \(state.status.isEmpty ? "clean" : "\(state.status.count)\(state.truncated ? "+" : "") changed or untracked path(s)") (as of \(stamp))"]
        for entry in state.status { lines.append("  - `" + line(entry) + "`") }
        if state.truncated { lines.append("  - … more not shown (limit \(GitState.statusLimit))") }
        return lines
    }

    private static func editedLines(_ files: [String]) -> [String] {
        guard !files.isEmpty else { return ["- Files edited: none recorded"] }
        let shown = files.prefix(30)
        var lines = ["- Files edited (\(files.count)):"]
        for file in shown { lines.append("  - `" + line(file) + "`") }
        if files.count > shown.count { lines.append("  - … \(files.count - shown.count) more") }
        return lines
    }

    private static func commandLines(_ records: [ToolCallRecord], limit: Int) -> [String] {
        let withCommand = records.filter { $0.command != nil }
        guard !withCommand.isEmpty else {
            return records.isEmpty ? ["- Commands: no tool calls recorded"] : ["- Commands: \(records.count) tool call(s) recorded, none with command text"]
        }
        let shown = withCommand.suffix(limit)
        var lines = ["- Commands (last \(shown.count) of \(withCommand.count), oldest first):"]
        for record in shown {
            let outcome: String
            switch record.result {
            case .succeeded: outcome = record.exitCode.map { "exit \($0)" } ?? "succeeded (exit code not reported)"
            case .failed: outcome = record.exitCode.map { "exit \($0)" } ?? "failed (exit code not reported)"
            case .unconfirmed: outcome = "result unconfirmed"
            }
            lines.append("  - `" + line(record.command ?? "").replacingOccurrences(of: "`", with: "'") + "` → " + outcome + " · " + iso(record.observedAt))
        }
        if withCommand.count > shown.count { lines.append("  - … \(withCommand.count - shown.count) earlier command(s) not shown") }
        return lines
    }

    private static func coverage(_ records: [ToolCallRecord], agent: SessionHistoryAgent) -> String {
        let sources = Set(records.map(\.source))
        var parts: [String] = []
        if sources.contains("hook") { parts.append("hook payloads report commands and exit codes") }
        if sources.contains("appserver") { parts.append("Codex app-server reports commands and exit codes") }
        let others = sources.subtracting(["hook", "appserver"]).sorted()
        if !others.isEmpty { parts.append("\(others.joined(separator: "/")) report tool names only (no command text, no exit code)") }
        if records.isEmpty { parts.append("no tool calls recorded for this session") }
        parts.append("the ledger keeps the last 50 calls per session for seven days")
        parts.append("prompts, outputs and reasoning are never recorded")
        return parts.joined(separator: "; ") + "."
    }

    private static func freshness(journalURL: URL, ledgerURL: URL, journalRead: Bool, ledgerRead: Bool, journalOldest: Date? = nil) -> String {
        func mtime(_ url: URL) -> String? {
            (try? FileManager.default.attributesOfItem(atPath: url.path)[.modificationDate] as? Date).map(iso)
        }
        // The journal is a bounded diagnostic (250 entries, seven days); a busy
        // agent can push a session's early transitions out within hours, so the
        // window's start is stated rather than implied.
        let window = journalOldest.map { ", covering transitions since \(iso($0)) (\(LifecycleJournal.maxEntries)-entry cap)" } ?? ""
        let journal = journalRead ? "lifecycle journal written \(mtime(journalURL) ?? "unknown")\(window)" : "lifecycle journal absent"
        let ledger = ledgerRead ? "tool ledger written \(mtime(ledgerURL) ?? "unknown") (last 50 calls per session)" : "tool ledger absent"
        return journal + "; " + ledger + "; git state is live."
    }

    // MARK: helpers

    private static func readLedger(url: URL) -> [String: [ToolCallRecord]] {
        guard let data = try? Data(contentsOf: url), data.count <= 8_000_000,
              let stored = try? JSONDecoder().decode([String: [ToolCallRecord]].self, from: data) else { return [:] }
        return stored
    }

    static func editedFiles(_ records: [ToolCallRecord]) -> [String] {
        let edits = records.filter { ToolActivity.phrase(for: $0.tool) == "Editing" || $0.tool.lowercased() == "patch" }
        return Array(Set(edits.flatMap(\.files).filter { $0.hasPrefix("/") })).sorted()
    }

    /// The repository most of the edited files live in; nil when none resolve.
    static func derivedCheckout(_ files: [String], git: GitProbe) -> String? {
        var counts: [String: Int] = [:]
        var probed: [String: String?] = [:]
        for file in files {
            let parent = URL(fileURLWithPath: file).deletingLastPathComponent().path
            if probed[parent] == nil {
                guard probed.count < 8 else { break }
                probed[parent] = git.probe(parent)?.root
            }
            if let root = probed[parent] ?? nil { counts[root, default: 0] += 1 }
        }
        return counts.max { $0.value == $1.value ? $0.key > $1.key : $0.value < $1.value }?.key
    }

    static func ticketCandidates(_ files: [String]) -> [String] {
        var seen = Set<String>()
        for file in files {
            let parts = file.split(separator: "/", omittingEmptySubsequences: false).map(String.init)
            guard let index = parts.firstIndex(of: ".scratch"), index + 1 < parts.count, !parts[index + 1].isEmpty else { continue }
            seen.insert(parts[...(index + 1)].joined(separator: "/"))
        }
        return seen.sorted()
    }

    private static func historyAgent(_ kind: AgentKind) -> SessionHistoryAgent? {
        switch kind {
        case .claudeCode: .claude
        case .codex: .codex
        case .cursor: .cursor
        case .grok: .grokBuild
        default: nil
        }
    }

    private static func kind(of agent: SessionHistoryAgent) -> AgentKind {
        switch agent {
        case .claude: .claudeCode
        case .codex: .codex
        case .cursor: .cursor
        case .grokBuild: .grok
        }
    }

    private static func iso(_ date: Date) -> String { ISO8601DateFormatter().string(from: date) }
    private static func line(_ text: String) -> String { text.components(separatedBy: .controlCharacters).joined(separator: " ") }
}
